### ISSUE TITLE
build が落ちる

### ISSUE THREAD

**Issue by tktcorporation** [tktcorporation/vrchat-photo-journey#115]
```
> vite build

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
vite v5.2.14 building for production...
transforming...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

assets/NotoSansCJKjp-Regular.ttf referenced in /home/runner/work/vrchat-photo-journey/vrchat-photo-journey/src/index.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
node_modules/.pnpm/@tanstack+react-query@4.36.1_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
✓ 2070 modules transformed.
rendering chunks...
computing gzip size...
out/index.html                   0.41 kB │ gzip:   0.29 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
out/assets/index-CSQvlr2o.css   [32](https://github.com/tktcorporation/vrchat-photo-journey/actions/runs/11428364262/job/31793531534#step:7:33).92 kB │ gzip:   6.58 kB
out/assets/index-BXLFjY3j.js   623.55 kB │ gzip: 197.74 kB │ map: 3,109.70 kB
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 5.28s

> vrchat-photo-journey@0.2.0-alpha.4 build:electron /home/runner/work/vrchat-photo-journey/vrchat-photo-journey
> tsc -p electron

Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 99, reused 65, downloaded 30, added 0
Progress: resolved 270, reused 182, downloaded 82, added 0
 WARN  8 deprecated subdependencies found: @npmcli/move-file@2.0.1, are-we-there-yet@3.0.1, gauge@4.0.4, glob@7.2.3, glob@8.1.0, inflight@1.0.6, npmlog@6.0.2, rimraf@3.0.2
Packages: +286
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 309, reused 216, downloaded 91, added 286, done
Error: Cannot find module 'uri-js'
Require stack:
- /home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab08[42](https://github.com/tktcorporation/vrchat-photo-journey/actions/runs/11428364262/job/31793531534#step:7:43)c3-86d/node_modules/.pnpm/ajv@6.12.6/node_modules/ajv/lib/compile/resolve.js
- /home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/ajv@6.12.6/node_modules/ajv/lib/compile/index.js
- /home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/ajv@6.12.6/node_modules/ajv/lib/ajv.js
- /home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/@develar+schema-utils@2.6.5/node_modules/@develar/schema-utils/dist/validate.js
- /home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/@develar+schema-utils@2.6.5/node_modules/@develar/schema-utils/dist/index.js
- /home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/app-builder-lib@25.1.8_dmg-builder@25.1.8_electron-builder-squirrel-windows@25.1.8/node_modules/app-builder-lib/out/util/config/config.js
- /home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/app-builder-lib@25.1.8_dmg-builder@25.1.8_electron-builder-squirrel-windows@25.1.8/node_modules/app-builder-lib/out/electron/electronVersion.js
- /home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/app-builder-lib@25.1.8_dmg-builder@25.1.8_electron-builder-squirrel-windows@25.1.8/node_modules/app-builder-lib/out/electron/ElectronFramework.js
- /home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/app-builder-lib@25.1.8_dmg-builder@25.1.8_electron-builder-squirrel-windows@25.1.8/node_modules/app-builder-lib/out/packager.js
- /home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/app-builder-lib@25.1.8_dmg-builder@25.1.8_electron-builder-squirrel-windows@25.1.8/node_modules/app-builder-lib/out/index.js
- /home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/electron-builder@25.1.8_electron-builder-squirrel-windows@25.1.8/node_modules/electron-builder/out/builder.js
- /home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/electron-builder@25.1.8_electron-builder-squirrel-windows@25.1.8/node_modules/electron-builder/out/cli/cli.js
- /home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/electron-builder@25.1.8_electron-builder-squirrel-windows@25.1.8/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function.Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/ajv@6.12.6/node_modules/ajv/lib/compile/resolve.js:3:11)
    at Module._compile (node:internal/modules/cjs/loader:1[46](https://github.com/tktcorporation/vrchat-photo-journey/actions/runs/11428364262/job/31793531534#step:7:47)9:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:15[48](https://github.com/tktcorporation/vrchat-photo-journey/actions/runs/11428364262/job/31793531534#step:7:49):10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/runner/.cache/pnpm/dlx/wjdgmwb7zjjknm4vag3cgha5cy/192ab0842c3-86d/node_modules/.pnpm/ajv@6.12.6/node_modules/ajv/lib/compile/index.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1[54](https://github.com/tktcorporation/vrchat-photo-journey/actions/runs/11428364262/job/31793531534#step:7:55)8:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
Error: Process completed with exit code 1.
```

**Comment by tktcorporation** [comment]
* https://github.com/tktcorporation/vrchat-photo-journey/pull/118

yarn に戻して解決した
